# syntax=docker/dockerfile:1.3
FROM python:3.11

RUN pip install --no-cache-dir requests==2.28.2

COPY launch_checks.sh /root/launch_checks.sh
COPY cgwire_checks.py /root/cgwire_checks.py
RUN chmod 555 /root/launch_checks.sh /root/cgwire_checks.py

CMD ["/root/launch_checks.sh"]
